dict_offensive = {
    "fdp":"filho da puta",
    "vtnc":"vai tomar no cu",
    "vsf":"vai se foder",
    "pnc":"pau no cu",
    "otr":"otário",
    "c*":"cu",
    "pqp":"puta que pariu",
    "krl":"caralho",
    "crl":"caralho",
    "fdc":"foda-se",
    "fds":"foda-se",
    "kct":"cacete",
    "karai":"caralho",
    "carai":"caralho",
    "crlh":"caralho",
    "kr1":"caralho",
    "c4ralho":"caralho",
    "cr4lho":"caralho",
    "caray":"caralho",
    "krll":"caralho",
    "fodase":"foda-se",
    "fdse":"foda-se",
    "foda":"foda",
    "f0da":"foda",
    "f*da":"foda",
    "fddo":"fudido",
    "fudido":"fudido",
    "fudida":"fudida",
    "puta":"puta",
    "put@":"puta",
    "pt*":"puta",
    "put4":"puta",
    "ptn":"puta que te pariu",
    "ptqp":"puta que pariu",
    "ptp":"puta que pariu",
    "filhadeput*":"filha da puta",
    "fdputa":"filha/filho da puta",
    "cu":"cu",
    "cú":"cu",
    "c0":"cu",
    "cuzao":"cuzão",
    "cuzão":"cuzão",
    "cuzinho":"cu (diminutivo)",
    "arrombado":"arrombado",
    "armbdo":"arrombado",
    "arrombada":"arrombada",
    "merda":"merda",
    "mrd":"merda",
    "m3rda":"merda",
    "merd4":"merda",
    "bosta":"bosta",
    "bst":"bosta",
    "b0sta":"bosta",
    "vtc":"vai tomar no cu",
    "tnc":"toma no cu",
    "tntc":"toma no teu cu",
    "cacete":"cacete",
    "cct":"cacete",
    "kacete":"cacete",
    "cct3":"cacete",
    "bct":"buceta",
    "buc":"buceta",
    "b*ceta":"buceta",
    "buc3ta":"buceta",
    "xota":"xoxota",
    "xxt":"xoxota",
    "xoxota":"xoxota",
    "ppk":"pepeka",
    "piroca":"piroca",
    "prc":"piroca",
    "piroka":"piroca",
    "pir0ca":"piroca",
    "rola":"rola",
    "r0la":"rola",
    "pau":"pau (pênis)",
    "p@u":"pau (pênis)",
    "babaca":"babaca",
    "escroto":"escroto",
    "escrt":"escroto",
    "vagabundo":"vagabundo",
    "vgb":"vagabundo",
    "vgbd":"vagabundo",
    "safado":"safado",
    "safada":"safada",
    "sfd":"safado",
    "canalha":"canalha",
    "cnl":"canalha",
    "desgraçado":"desgraçado",
    "dsgrd":"desgraçado",
    "inútil":"inútil",
    "inutl":"inútil",
    "anta":"anta (idiota)",
    "panaca":"panaca",
    "pnkc":"panaca",
    "retardado":"retardado",
    "rtd":"retardado",
    "imbecil":"imbecil",
    "idiota":"idiota",
    "lixo":"lixo (insulto)",
    "nojento":"nojento",
    "nojenta":"nojenta",
    "corno":"corno",
    "crn":"corno",
    "cornão":"corno (intensivo)",
    "miserável":"miserável",
    "msrvl":"miserável",
    "palhaço":"palhaço",
    "plhc":"palhaço",
    "cadela":"cadela",
    "cdl":"cadela",
    "vadia":"vadia",
    "piranha":"piranha (insulto)",
    "galinha":"galinha (insulto)",
    "trouxa":"trouxa",
    "trxa":"trouxa",
    "vacilão":"vacilão",
    "vcl":"vacilão",
    "lazarento":"lazarento",
    "burro":"burro (insulto)",
    "burra":"burra (insulto)",
    "jegue":"jegue (burro)",
    "infeliz":"infeliz (insulto)",
    "viado":"viado",
    "vdo":"viado",
    "vi@do":"viado",
    "boiola":"boiola",
    "baitola":"baitola",
    "traveco":"traveco",
    "sapatão":"sapatão",
    "sptao":"sapatão",
    "macaco":"macaco (slur racial)",
    "mk0":"macaco (slur racial)",
    "fdp!":"filho da puta",
    "v4i s3 f0d3r":"vai se foder",
    "f1lho d4 puta":"filho da puta"
}